### ISSUE TITLE
Incorrect singularization of the word

### ISSUE THREAD

**Issue by Serproger** [bricelam/EFCore.Pluralizer#11]
The word "Purchases" is singularized as "Purchas". Please fix it.

**Comment by bricelam** [comment]
The pluralizer in this repo is intended to be fully compatible with the EF6 pluralizer. Any bug fixes or improvements to pluralization will break that compatibility.

Feel free to fork this repo and/or use a better pluralizer like [Humanizer](https://github.com/Humanizr/Humanizer).
