### ISSUE TITLE
Table name of CommunicationStatus singularized to CommunicationStatu

### ISSUE THREAD

**Issue by ProfSantosh** [bricelam/EFCore.Pluralizer#14]
Hello, Brice!
I'm having trouble using pluralizer on NETCore 3.1 + EFCore.3.1.2.

I have a table called `CommunicationStatus` and on `Scaffold-DbContext` the model it creates is called `CommunicationStatu` this only happened after installing the `EFCore.Pluralizer`

The leading `s` in Status should not be stripped out.

Thanks

**Comment by ErikEJ** [comment]
Duplicate of #11 ?
