### ISSUE TITLE
Won't work if parameter '-UseDatabaseNames' is used

### ISSUE THREAD

**Issue by figofan** [bricelam/EFCore.Pluralizer#17]
This package works perfectly without parameter '-UseDatabaseNames', is there a workaround if I must use this parameter?

**Comment by ErikEJ** [comment]
This has been fixed in EF Core 5.

**Comment by figofan** [comment]
> This has been fixed in EF Core 5.

EF Core 5 won't come out until Nov, I guess I'll just add the plural manually. Thank you anyway!

**Comment by bricelam** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/12102

**Comment by bricelam** [comment]
P.S. EF Core 5.0 RC1 does have a go-live license. There will only be a handful of additional bugs fixed between now and November 10.

**Comment by bricelam** [comment]
In other words, you can think of RC2 and GA as the usual monthly patch releases but for early adopters.
