### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by VasuInukollu** [bricelam/EFCore.Pluralizer#7]
dotnet publish is resulting in this error

Error:
  An assembly specified in the application dependencies manifest (Manager.deps.json) was not found:
    package: 'Bricelam.EntityFrameworkCore.Pluralizer', version: '1.0.0'
    path: 'lib/netstandard2.0/Bricelam.EntityFrameworkCore.Pluralizer.dll'

**Comment by bricelam** [comment]
Does this still repro? Did you happen to be using an AppX package?
