### ISSUE TITLE
Support for .Net Core 3.0

### ISSUE THREAD

**Issue by IoTFier** [bricelam/EFCore.Pluralizer#8]
Hi @bricelam ,

Any plan to upgrade this package to support .Net Core 3.0 ?

Thank you

**Comment by bricelam** [comment]
Did it break? lol, I'll put it on my TODO list.

**Comment by IoTFier** [comment]
Hi @bricelam ,

It didn't create plurals for collections.
In my App, I am using .Net Core (3.0) to build my services layer and Sqlite database. I have opted for the DB first approach
• created my db schema using Sqlitebrower utility
• generated scaffolding code using .Net EF Core CLI via PMC (package management console in VS 2019). It was working flawlessly up until EF Core 2.2.
• I am using the Scaffold-DbContext API to write context, output files in separate folder

As a result (after upgrading .Net EF Core 2.2 to) the .Net EF Core 3.0 is failing to add using statement in the generated dbContext class to refer to the entity classes written in their own folder. 
**So, this is a .Net Core 3.0 bug.**

**May be this is what's breaking / stopping your NuGet to run beyond that ?**

Thoughts ?

**Comment by ErikEJ** [comment]
Maybe you misunderstand the API?

https://github.com/aspnet/EntityFrameworkCore/issues/18238

**Comment by bricelam** [comment]
Wasn't the ability to put the DbContext in a separate directory only added in 3.0? It looks like you're hitting https://github.com/aspnet/EntityFrameworkCore/issues/17839

**Comment by IoTFier** [comment]
No. It was available even before that (2.1, 2.2)

**Comment by IoTFier** [comment]
> Maybe you misunderstand the API?
> 
> [aspnet/EntityFrameworkCore#18238](https://github.com/aspnet/EntityFrameworkCore/issues/18238)

I don't think so. I have used the same API prior to .Net Core 3.0

**Comment by IoTFier** [comment]
Hi @bricelam - any thoughts ?

**Comment by bricelam** [comment]
About what?

**Comment by bricelam** [comment]
Closing. I'm not seeing any issues with using this on .NET Core 3.0 with EF Core 3.0...

**Comment by bricelam** [comment]
(If you're seeing bugs in EF Core, submit an issue there)
