### ISSUE TITLE
Scaffolding with EFCore 3 for custom field names and Plurals

### ISSUE THREAD

**Issue by paulovila** [bricelam/EFCore.Pluralizer#9]
It would be good to have the IPluralizer for scaffolding in netcore 3, and also being able to intercept names of any field in the schema, for example , if I had a SQL column called FXRate, I'd like that the scaffolding to respect that name or else I could intercept it and say
 ``` -UseDatabaseNames```  in ```Scaffold-DbContext``` doesn't respect the pluralization.

**Comment by bricelam** [comment]
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12102

**Comment by ErikEJ** [comment]
Working on this in EF Core Power Tools: https://github.com/ErikEJ/EFCorePowerTools/pull/317
